# -*- coding: utf-8 -*-
"""Varias_Muestras_tarea

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YVVl-vdFXIzF1Qocsr5HMBm2bkB1EkH9
"""

import scipy.stats as stats
import math

#  Ejercicio 1
n1, x1, s1 = 10, 25, 4
n2, x2, s2 = 12, 28, 3.5
alpha1 = 0.05

se1 = math.sqrt((s1**2 / n1) + (s2**2 / n2))
t_stat1 = (x1 - x2) / se1
df1 = ((s1**2 / n1 + s2**2 / n2)**2) / ((s1**2 / n1)**2 / (n1 - 1) + (s2**2 / n2)**2 / (n2 - 1))
p_value1 = 2 * (1 - stats.t.cdf(abs(t_stat1), df1))

# Ejercicio 2
n1, x1, s1 = 20, 0.5, 0.1
n2, x2, s2 = 20, 0.45, 0.08
alpha2 = 0.01

se2 = math.sqrt((s1**2 / n1) + (s2**2 / n2))
t_stat2 = (x1 - x2) / se2
df2 = ((s1**2 / n1 + s2**2 / n2)**2) / ((s1**2 / n1)**2 / (n1 - 1) + (s2**2 / n2)**2 / (n2 - 1))
p_value2 = 2 * (1 - stats.t.cdf(abs(t_stat2), df2))

#  Ejercicio 3
n1, x1, s1 = 15, 200, 15
n2, x2, s2 = 18, 190, 10
alpha3 = 0.05

se3 = math.sqrt((s1**2 / n1) + (s2**2 / n2))
t_stat3 = (x1 - x2) / se3
df3 = ((s1**2 / n1 + s2**2 / n2)**2) / ((s1**2 / n1)**2 / (n1 - 1) + (s2**2 / n2)**2 / (n2 - 1))
p_value3 = 2 * (1 - stats.t.cdf(abs(t_stat3), df3))

#  Resultados
results = {
    "Ejercicio 1": {
        "t": t_stat1,
        "df": df1,
        "p": p_value1,
        "rechazar_H0": p_value1 < alpha1
    },
    "Ejercicio 2": {
        "t": t_stat2,
        "df": df2,
        "p": p_value2,
        "rechazar_H0": p_value2 < alpha2
    },
    "Ejercicio 3": {
        "t": t_stat3,
        "df": df3,
        "p": p_value3,
        "rechazar_H0": p_value3 < alpha3
    }
}

for ej, res in results.items():
    print(f"\n{ej}:")
    print(f"  t = {res['t']:.4f}")
    print(f"  gl = {res['df']:.2f}")
    print(f"  p-valor = {res['p']:.4f}")
    print(f"  ¿Rechazar H₀?: {'Sí' if res['rechazar_H0'] else 'No'}")