# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kOmUT10MJ08GNSa1kx4jUKIygfBTU8XX
"""

#Ejercicio 1 greafico de dispersion
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import pearsonr

# Datos
datos1 = pd.DataFrame({
    'Estudiante': ['A','B','C','D','E','F','G'],
    'Horas de estudio': [2, 3, 4, 5, 6, 7, 8],
    'Calificación': [50, 55, 65, 70, 75, 82, 90]
})

# Gráfico de dispersión
plt.scatter(datos1['Horas de estudio'], datos1['Calificación'], color='blue')
plt.title('Horas de estudio vs Calificación')
plt.xlabel('Horas de estudio')
plt.ylabel('Calificación')
plt.grid(True)
plt.show()

# Cálculo del coeficiente de Pearson
coef_pearson, p_valor = pearsonr(datos1['Horas de estudio'], datos1['Calificación'])
print(f"Coeficiente de correlación de Pearson: {coef_pearson:.4f}")

#Ejercicio 1 grafico de dispersion
import matplotlib.pyplot as plt
import pandas as pd

# Datos del ejercicio 2
datos2 = pd.DataFrame({
    'Atleta': ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
    'Competencia A': [1, 3, 2, 5, 6, 4, 7],
    'Competencia B': [2, 4, 1, 6, 5, 3, 7]
})

# Gráfico de dispersión
plt.figure(figsize=(6, 5))
plt.scatter(datos2['Competencia A'], datos2['Competencia B'], color='green')
plt.title('Ejercicio 2: Competencia A vs Competencia B')
plt.xlabel('Ranking Competencia A')
plt.ylabel('Ranking Competencia B')
plt.grid(True)
plt.show()

datos3 = pd.DataFrame({
    'Producto': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Juez 1': [1, 2, 3, 4, 5, 6],
    'Juez 2': [2, 1, 3, 4, 6, 5]
})

# Gráfico de dispersión
plt.figure(figsize=(6, 5))
plt.scatter(datos3['Juez 1'], datos3['Juez 2'], color='red')
plt.title('Ejercicio 3: Ranking Juez 1 vs Juez 2')
plt.xlabel('Ranking Juez 1')
plt.ylabel('Ranking Juez 2')
plt.grid(True)
plt.show()

from scipy.stats import spearmanr

# Datos
datos2 = pd.DataFrame({
    'Atleta': ['A','B','C','D','E','F','G'],
    'Competencia A': [1, 3, 2, 5, 6, 4, 7],
    'Competencia B': [2, 4, 1, 6, 5, 3, 7]
})

# Cálculo del coeficiente de Spearman
coef_spearman, p_valor = spearmanr(datos2['Competencia A'], datos2['Competencia B'])
print(f"Coeficiente de correlación de Spearman: {coef_spearman:.4f}")

from scipy.stats import kendalltau

# Datos
datos3 = pd.DataFrame({
    'Producto': ['A','B','C','D','E','F'],
    'Juez 1': [1, 2, 3, 4, 5, 6],
    'Juez 2': [2, 1, 3, 4, 6, 5]
})

# Cálculo del coeficiente de Kendall
coef_kendall, p_valor = kendalltau(datos3['Juez 1'], datos3['Juez 2'])
print(f"Coeficiente Tau de Kendall: {coef_kendall:.4f}")