# -*- coding: utf-8 -*-
"""REGRESION MULTIPLE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPJ4v0eI7oVFp3qYujp0v8w8aAvYCVM6
"""

import pandas as pd
import statsmodels.api as sm

# --- 1️⃣ Leer Excel ---
# Asegúrate de poner el nombre exacto del archivo con extensión .xlsx
file_path = 'hurricane_erin_case_study.xlsx'

# Leer la hoja 'data'
data = pd.read_excel(file_path, sheet_name='data')

# --- 2️⃣ EDA Básico ---
print("Primeras filas de los datos:")
print(data.head())

print("\nInformación general:")
print(data.info())

print("\nEstadísticas descriptivas:")
print(data.describe())

# --- 3️⃣ Preparar regresión múltiple ---
# Seleccionamos variables independientes
X = data[['max_wind_kts', 'rainfall_mm_per_hr', 'distance_to_SantoDomingo_km']]
y = data['power_outages']

# Agregamos constante para el intercepto
X = sm.add_constant(X)

# Ajustamos el modelo
model = sm.OLS(y, X).fit()

# --- 4️⃣ Resultados ---
print("\nEcuación estimada:")
print(model.params)

print("\nSignificancia global (F-test):")
print(f"F-statistic: {model.fvalue}, p-value: {model.f_pvalue}")

print("\nSignificancia individual de coeficientes (p-values):")
print(model.pvalues)

print("\nR² y resumen completo:")
print(model.summary())